### ISSUE TITLE
Allow for .and(When(...)...) to concatenate multiple start conditions

### ISSUE THREAD

**Issue by centigrade-julian-lang** [Centigrade/ngtx#33]
### Description

In real tests we can utilize classes to be DRY when it comes to setting up tests like this:

~~~ts

class the {
  static InfoIcon() {
     return get('.info');
  }
}

class Once {
   static InfoIconClicked() {
        return When(host).has(state({...})). and(the.InfoIcon).gets(clicked);
   }
}

it('should call something when clicking the info icon', () => {
    Once.InfoIconClicked().expect(host).to(haveCalled(...));
});

it('should not call something on click when the InfoIcon is disabled', () => {
     Once.InfoIconClicked().and(host).has(state({ disabled: true })).expect(host).to(haveCalled(...));
});
~~~

In some cases we need to setup tests with two or more setup functions like seen above. In  these cases we're out of luck, since there is no way to combine `When` with an already started test expression.

### Proposed solution

It should be allowed and possible to combine `When` by passing it to an `.and(When...)` block

**Comment by JulianLang** [comment]
Shipped.

**Comment by centigrade-julian-lang** [comment]
Shipped in alpha version
