### ISSUE TITLE
Also update the README on npm package

### ISSUE THREAD

**Issue by JulianLang** [Centigrade/ngtx#7]
- I currently have no access to the `@centgirade/ngtx` package on npm - so cannot do it myself.
- Here is the way how to update the README on npm: https://docs.npmjs.com/about-package-readme-files
- The content of README.md is already updated in this repository (https://github.com/Centigrade/ngtx/pull/6)

**Comment by centigrade-julian-lang** [comment]
Done in https://github.com/Centigrade/ngtx/pull/10
