### ISSUE TITLE
ngtx does not work with Angular 12 project and jest

### ISSUE THREAD

**Issue by JulianLang** [Centigrade/ngtx#9]
## Repro

- Create a blank Angular 12 project with cli
- Add ngtx as dev dependency
- Adjust app test to minimally use ngtx (e.g. only initialize ngtx with `useFixture(fixture)`)
- `$ npm run test` -> ngtx works without warnings or errors
- Migrate to jest, e.g. using https://dev.to/alfredoperez/angular-10-setting-up-jest-2m0l
- `npm run test` again, depending on jest configuration and tooling, different errors occur, e.g.
   - https://github.com/kulshekhar/ts-jest/issues/937

**Comment by centigrade-julian-lang** [comment]
Looks like we need to pacakge the library in a way that offers different platforms. This can be done by adding these properties to the `package.json`:

~~~jsonc
{
  // ...
  "main": "./bundles/core.umd.js",
  "fesm2015": "./fesm2015/core.js",
  "esm2015": "./esm2015/core.js",
  "typings": "./core.d.ts",
  "module": "./fesm2015/core.js",
  "es2015": "./fesm2015/core.js",
}
~~~
